virt-manager: Autospec creation for update from version 1.4.3 to version 1.5.0
Andrew Wong (2):
      virtinst: Fix _URLFetcher for reading files
      virtinst: Use isoinfo to extract files from ISOs and block devices

Anthony (1):
      ui: create: fix bootstrap typo

Chen Hanxiao (3):
      pycodestyle: fix all E125 warnings
      pylint: Replace deprecated assertEquals with assertEqual
      pylint: remove a unnecessary pass

Cole Robinson (97):
      tests: Add basic hostkeymap test
      tests: Add more hostkeymap tests
      systray: Use APPLICATION_STATUS for appindicator
      engine: Don't attempt --test-first-run if --connect passed
      tests: Convert file()->open() usage
      cli: Fix OrderedDict mutated during iteration on python3
      xmlnsqemu: Order XML output like libvirt does
      virtconv: Don't implicitly depend on dict hash order
      cli: Make _VirtCLIArgument instantiation less crazy
      uitests: launch UI with same python executable
      manager: Drop python2 only cmp() usage
      urlfetcher: Write test file as binary content
      tests: uitests: wire up --debug option
      tests: xmlparse: explain AddRemoveDevice cases
      devicepanic: Don't return empty model list (bz #1505532)
      addhardware: Don't allow panic option where it isn't supported
      addhardware: Fix virtio-scsi controller target calculation
      tests: test_urls: Update URL list
      details: Remove q35 support warning (bz #1443021)
      gfxdetails: Select rendernode by default when user requests gl=on
      guest: Set default rendernode= if spice gl requested
      virtinst: Drop UUID validation
      virtinst: network: Don't generate UUID by default
      virtinst: storage: Don't generate UUID by default
      tests: Remove storage UUID hackery
      connection: Another py3 exception variable fix
      baseclass: Fix UI file loading on py3
      tests: clitest: Add an actual stub iso for --location testing
      urlfetcher: More debian CD arch handling
      urlfetcher: Fix detection with latest ALT media
      tests: test_urls: Big rework
      tests: test_urls: Simplify adding in local tests
      tests: Drop --skipcli option
      spec: Add dep on genisoimage, for isoinfo
      tests: cli: Skip iso test if isoinfo isn't installed
      tests: Don't always generate coverage data
      tests: Force verbose mode for UI tests
      uitests: Make unittest.installHandler work as expected
      tests: Rework how we pass command line objects down to test data
      virt-manager: Gracefully exit app on ctrl-c, not sys.exit
      uitests: Split out UITestCase class
      uitests: Centralize app shutdown
      uitests: Drop redundant sleeps
      uitests: Drop sleeps from newvm tests
      virt-manager: If --connect passed, wait for it to init
      uitests: Wire up --coverage
      config: Use memory backend with --test-first-run
      uitests: Add test for 'about' dialog
      ui: about: Bump copyright year
      uitests: Add preferences dialog tests
      config: Explain and simplify our gsettings wrapper a bit
      error: Add accessible strings for error dialogs
      manager: Add accessible names to conn context menu
      ui: connect: Add 'Custom URI' option
      uitests: Add 'open connection' testing
      uitests: Wait for windows to become 'active'
      uitests: Move helper functions into the Node wrapper class
      uitests: Centralize object list smoketest handling
      ui: Add createnet/pool/vol/interface tests
      uitests: connect: Fix failure case to always fail
      snapshots: Maintain selection after refresh
      uitests: Add snapshot tests
      watchdog: Add proper label for 'dump' action
      uitests: Add a bunch of addhardware testing
      uitests: s/find_pattern/find/g
      utils: Have find 'name' match labeller text too
      uitests: addhardware: add network tests
      uitests: addhardware storage/disk testing
      addhardware: Don't allow adding floppy controller
      uitests: addhardware controller tests
      uitests: addhardware error dialog tests
      uitests: newvm: Add a customize->addhardware test
      uitests: Basic migration tests
      uitests: Add choosecd dialog tests
      uitests: Add dbus remote cli test
      uitests: Add manager related tests
      uitests: Add details editing tests
      details: Tweak sound hwlist entry to be consistent with others
      uitests: More details config tweaking
      uitests: prefs: Move helper functions to util
      uitests: Add live console tests
      uitests: console: Add live lxc serial test
      uitests: xml: drop hardcoded emulator path
      console: Add a basic spice GL + usbredir test
      uitests: Add a live hotplug and media change test
      uitests: Add a test for command line errors
      tests: Add 'magicuri' helper
      cli: Share find_inst_cb logic
      tests: urls: Tweak output and logging a bit
      tests: inject: Small updates
      addhardware: Only add virtio-scsi if no other scsi controllers present
      tests: urls: Fix pylint
      Drop more cmp() usage for python3
      tests: inject: Fix some pylint
      cli: Drop python2ism with OSError
      man: Fix libvirt doc reference for startup_policy
      Prep for release 1.5.0

Cédric Bosdonnat (5):
      py3: store exception variables for use outside except
      python3: fix bytes/string mess in serial console
      Improve container image url examples
      oscontainer: ask root password in the wizard
      Unify invisible_char values

David Rabel (1):
      Fix typo in virt-convert man page

Jia He (1):
      Add arm64 check to urlfetcher to cater for Debian based distro

Jim Fehlig (1):
      virtinst: ignore comments in keymap conf files

Lin Ma (14):
      network: add support for parsing/formatting SR-IOV VFs
      host: Show details about the network of SR-IOV VF pool
      network: Set bridge name to None instead of blank
      testdriver: Add vhostuser example
      details: Show controller description + index
      testdriver: add missing addrStr for scsi disk
      addhardware: Correctly calculate virtio-scsi controller index
      addhardware: Remove IDE from list while adding controllers
      virtinst: Add a compare_controller function for future use
      virtinst: Add pretty_desc function for device address printing
      details: Rename the variable 'dev' to 'controller' in refresh_controller_page
      ui: details: Add ui for showing attached controller devices in the future
      details: Disallow removing the scsi controller if disks attached to it
      details: Show attached disk information in scsi controller page

Menno Lageman (1):
      virtinst: Add NUMA distance support

Pavel Hrdina (8):
      domain: don't add URI into params for tunneled migration
      urlfetcher: fix kernel/initrd paths for Ubuntu install CD
      diskbackend: convert to long the calculated size
      diskbackend: get a proper size of existing block device while cloning
      delete: undefine only persistent domain
      virtinst.support: fix copy&paste error
      cli: append "--attach" to virt-viewer if graphics has listen type none
      vnc: don't skip authentication for listen type none with fixed QEMU

Radostin Stoyanov (16):
      progress: Remove trailing white space
      pycodestyle: Use isinstance() for type checking
      pycodestyle: Remove description of fixed errors
      progress: Remove unused import
      progress: Don't overwrite "format"
      Convert iteritems() to items()
      Remove deprecated statvfs module
      Replace StringIO with io.(StringIO or BytesIO)
      Do not compare between None and int
      Use reload() from imp module
      Import reduce() from functools module
      Replace 'StandardError' with 'Exception'
      Use enumerate instead of range and len
      systray: Remove redundant variable assignment
      news: Fix typo
      Python 2/3 division compatability

Rauno Väli (1):
      devicedisk: copy all rbd pool host and auth for volume

Scott Garfinkle (1):
      virtio-scsi by default on power

Wim ten Have (1):
      virtinst: add vcpupin support